#!/bin/bash

echo "Starting bootstrapping.."
sleep .5
echo "..."
sleep .5

set -e

# Flag to only install dotfiles and not packages
skip_packages="${1}"

# This gets the OS of current machine. 
MY_OS="$(uname -s)"

MY_DISTRO="none"

# Current working directory. We'll need to come back to this later
INITIAL_WORKING_DIRECTORY=$(pwd)

# Directory of install script
SCRIPT_DIRECTORY=$(dirname "$0")


###############################################################################
# Find OS and Distro Name
###############################################################################

function no_packages() {
cat << EOF
Can't install packages on this device. 

Package installation is not supported on you OS or Distro

Please install any packages on your own. The list of of packages are located at:
    
    https://github.com/abasnfarah/dotfiles/blob/main/install

To install without packages, re-run the script with the following flag
    
    bash <(https://github.com/abasnfarah/dotfiles/blob/main)> --skip-packages
EOF
}


case $MY_OS in 
    Darwin*) 
        MY_OS="macOS" && MY_DISTRO="macOS"
        ;;
    Linux*) 
        MY_OS="Linux"
        
        if [ -f "/etc/arch-release" ]; then
            MY_DISTRO="Arch"
        else
            if  [ -f "/etc/debian_version" ]; then
                MY_DISTRO="Ubuntu"
            else
                [ -z "${skip_packages}" ] && no_packages
            fi
        fi
        ;;
    *)
        MY_OS="Other"
        [ -z "${skip_packages}" ] && no_packages
        
        ;;
esac

###############################################################################
# Install packages using OS or distro package manager
###############################################################################


function install_macos {
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/abasnfarah/dotfiles/HEAD/brew.sh)"
}

function install_arch {
    /bin/bash -c "$(curl -fLo https://raw.githubusercontent.com/abasnfarah/dotfiles/HEAD/arch.sh)"
}

function install_ubuntu { 
    /bin/bash -c "$(curl -fLo https://raw.githubusercontent.com/abasnfarah/dotfiles/HEAD/ubuntu.sh)"
}

echo "Your OS is $MY_OS"
echo "Your Distro is $MY_DISTRO"

if [ -z "${skip_packages}" ] ; then 

    if [ $MY_OS = "macOS" ]; then 
        install_macos
    elif [ $MY_OS = "Linux"] && [ $MY_DISTRO = "Arch"]; then 
        install_arch
    elif [ $MY_OS = "Linux" ] && [ $MY_DISTRO = "Ubuntu" ]; then 
        install_ubuntu
    fi

fi

###############################################################################
# TODO: Installing dotfiles
###############################################################################

function create_dotfiles_path {
    
    if [ ! -d "$1" ]; then
        mkdir "$1"
    else 
        echo "$1 directory already exists"
    fi

}

# Gets the absolute path of dotfiles_path
read -rep $'\nWhere do you want your dotfiles to live [~/workspaces/dotfiles]? ' dotfiles_path
eval dotfiles_path="${dotfiles_path:-"${HOME}/workspaces/dotfiles"}"

if [ ! $MY_OS = "macOS" ]; then
    dotfiles_path=$(realpath $dotfiles_path)
fi

# Clone dotfiles to dotfiles_path
echo "Installing dotfiles to the following directory: $dotfiles_path"
git clone https://github.com/abasnfarah/dotfiles "$dotfiles_path"

###############################################################################
# Install Plug (vim plugin manager) 
###############################################################################

curl -fLo ${HOME}/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  
###############################################################################
# Install tpm (tmux plugin manager)
###############################################################################

git clone https://github.com/tmux-plugins/tpm ${HOME}/.tmux/plugins/tpm

###############################################################################
# Create symlinks for dotfiles 
###############################################################################

ln -fs "${dotfiles_path}/zsh/.zshrc" "${HOME}/.zshrc"
ln -fs "${dotfiles_path}/zsh/.local.zsh" "${HOME}/.local.zsh"
ln -fs "${dotfiles_path}/zsh/.aliases.zsh" "${HOME}/.aliases.zsh"
ln -fs "${dotfiles_path}/vim/.vimrc" "${HOME}/.vimrc"
ln -fs "${dotfiles_path}/tmux/.tmux.conf" "${HOME}/.tmux.conf"

if [ $MY_OS = "Linux" ]; then
    ln -fs "${dotfiles_path}/arch/.config" "${HOME}/.config"
fi

if [ ! -d "${HOME}/.ssh" ]; then
    mkdir "${HOME}/.ssh"
fi

ln -fs "${dotfiles_path}/ssh/config" "${HOME}/.ssh/config"


###############################################################################
# Installing vim plugins  
###############################################################################

echo "Installing Vim Plugins... "

vim -E +PlugInstall +qall || true


###############################################################################
# ur machine is a potato now 
###############################################################################

cat << EOF 
All dotfiles have been succesfully installed.

To checkout the dotfiles code and other goodies go here:

    https://github.com/abasnfarah/dotfiles

Time to get cracking!!
EOF


exit 0
