# Exports workspaces and dotfiles location 
export WORKSPACES="${HOME}/workspaces"
export DOTFILES="${WORKSPACES}/dotfiles"

MY_OS="$(uname -s)"

case $MY_OS in 
    Darwin*) 
        if [ -f "/opt" ]; then # ARM
            # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
            source $DOTFILES/zsh/mac/arm.zsh
            source $(brew --prefix)/opt/powerlevel10k/powerlevel10k.zsh-theme
            source $(brew --prefix)/opt/zsh-syntax-highlighting/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

            export NVM_DIR="$HOME/.nvm"
              [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
              [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

        else # x86_64
            source $DOTFILES/zsh/mac/x86_65.zsh
            source $(brew --prefix)/share/powerlevel10k/powerlevel10k.zsh-theme
            source $(brew --prefix)/share/zsh-syntax-highlighting/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
        fi
        ;;
    Linux*) 
        if [ -f "/etc/arch-release" ]; then
            source $DOTFILES/zsh/arch/arch.zsh
            source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
            source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh # arch
        fi
        ;;
esac

source ~/.local.zsh

source ~/.aliases.zsh
source ~/.plugins.zsh


# Adds hidden files to FZF 
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -l -g ""'
export GPG_TTY=$(tty)

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

