# Exports workspaces and dotfiles location 
export WORKSPACES="${HOME}/workspaces"
export DOTFILES="${WORKSPACES}/dotfiles"

source ~/.local.zsh

source ~/.aliases.zsh
source ~/.plugins.zsh

# Arch config for dual monitors
#source ~/.screenlayout/two_monitor_layout.sh

# FZF setup 
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh # mac
source /usr/share/fzf/key-bindings.zsh # arch
source /usr/share/fzf/completion.zsh # arch 
# Adds hidden files to FZF 
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -l -g ""'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
# source $(brew --prefix)/opt/powerlevel10k/powerlevel10k.zsh-theme # mac
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme # arch

# Sourcing zsh-syntax-highligting
# source $(brew --prefix)/opt/zsh-syntax-highlighting/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh # mac
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh # arch

export GPG_TTY=$(tty)

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# export NVM_DIR="$HOME/.nvm"
#   [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
#   [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
